sudo: required
services:
  - docker

before_install:
  - docker build -t kwlooi/docker-react -f Dockerfile.dev .

script:
  - docker run --rm kwlooi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-716953936909"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $aws-access-key
  secret_access_key:
    secure: $aws-secret-key